version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${EXTERNAL_PORT}:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:${MONGO_PORT}/meteor
      PORT: 3000

  mongo:
    image: mongo:latest
    ports:
      - '${MONGO_PORT}:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
